flower = read.csv("flower.csv", header = FALSE)
str(flower)
flowerMatrix = as.matrix(flower)
str(flowerMatrix)
flowerVector = as.vector(flowerMatrix)
str(flowerVector)
distance1 = dist(flowerVector, method = "euclidean")
distance2 = dist(flower, method = "euclidean")
clusterIntensity = hclust(distance1, method = "ward")
plot(clusterIntensity)
rect.hclust(clusterIntensity, k=3 , border = "red")
flowerClusters = cutree(clusterIntensity, k=3)
flowerClusters
tapply(flowerVector, flowerClusters , mean)
dim(flowerClusters) = c(50,50)
image(flowerClusters, axes=FALSE, col = grey(seq(0,1,length = 256)))
image(flowerMatrix, axes=FALSE, col = grey(seq(0,1,length=256)))
