emails = read.csv("energy_bids.csv", stringsAsFactor = FALSE)
strwrap(emails$email[1])
table(emails$responsive)
mycorpus = Corpus(VectorSource(emails$email))
mycorpus[[1]]$content
mycorpus = tm_map(mycorpus, tolower)
mycorpus = tm_map(mycorpus, PlainTextDocument)
mycorpus = tm_map(mycorpus, removePunctuation)
mycorpus = tm_map(mycorpus, removeWords, stopwords("english"))
mycorpus = tm_map(mycorpus, stemDocument)
DTM = DocumentTermMatrix(mycorpus)         ##bag of words
DTM = removeSparseTerms(DTM,0.97)
term = as.data.frame(as.matrix(DTM))
colnames(term) = make.names(colnames(term))
term$responsive = emails$responsive
library(caTools)
set.seed(144)
split = sample.split(term$responsive, SplitRatio = 0.7)
traindata = subset(term, split == TRUE)
testdata = subset(term, split == FALSE)
library(rpart)
library(rpart.plot)
termCart = rpart(responsive~., data = traindata, method = "class")
prp(termCart)
predictCart = predict(termCart, newdata = testdata, type = "class")
table(testdata$responsive, predictCart)
termRF = randomForest(responsive~., data = traindata)
predictRF = predict(termRF, newdata =  testdata)
table(testdata$responsive, predictRF)
termglm = glm(responsive~., data = traindata , family = "binomial")
predictglm = predict(termglm, newdata = testdata, type = "binomial")
table(testdata$responsive, predictglm>0.5)
library(ROCR)
predictROCR = prediction(predictCart, testdata$responsive) 
prefROCR = performance(predictROCR, "trp", "frp")
plot(prefROCR, colorize = TRUE)
performance(prefROCR, "auc")@y.values
