library(tm)
library(SnowballC)
tweets = read.csv("tweets.csv", stringsAsFactors = FALSE)
tweets$Neg = as.factor(tweets$Avg <= -1)
table(tweets$Neg)
mycorpus = Corpus(VectorSource(tweets$Tweet))
mycorpus[[1]]$content
mycorpus = tm_map(mycorpus, tolower)
##mycorpus = tm_map(mycorpus, PlainTextDocument )
mycorpus = tm_map(mycorpus, removePunctuation)
mycorpus = tm_map(mycorpus, removeWords, c("apple",stopwords("english")))
mycorpus = tm_map(mycorpus, stemDocument)
frequen =  DocumentTermMatrix(mycorpus)
inspect(frequen[1000:1005,500:515])
findFreqTerms(frequen, lowfreq = 30)
sparse = removeSparseTerms(frequen, 0.995)
sparseDF = as.data.frame(as.matrix(sparse))
colnames(sparseDF) = make.names(colnames(sparseDF))
sparseDF$Neg = tweets$Neg
library(caTools)
set.seed(123)
split = sample.split(sparseDF$Neg,SplitRatio =0.7)
traindata = subset(sparseDF, split == TRUE)
testdata = subset(sparseDF, split == FALSE)
library(rpart)
library(rpart.plot)
tweetsCart = rpart(Neg ~ ., data = traindata, method = "class")
prp(tweetsCart)
predictCart = predict(tweetsCart, newdata = testdata, type = "class")
table(testdata$Neg, predictCart)
library(randomForest)
tweetsRF = randomForest(Neg~., data = traindata)
predictRF = predict(tweetsRF, newdata = testdata)
table(testdata$Neg, predictRF)
tweetsLog = glm(Neg~., data = traindata, family = "binomial")
predictglm = predict(tweetsLog, newdata = testdata, type = "response")
table(testdata$Neg, predictglm>0.5)
