wiki = read.csv("wiki.csv", stringsAsFactor = FALSE)
table(wiki$Vandal)
library(tm)
library(SnowballC)
corpusAdded = Corpus(VectorSource(wiki$Added))
corpusAdded = tm_map(corpusAdded, removeWords, stopwords("english"))
length(stopwords("english"))
corpusAdded = tm_map(corpusAdded, stemDocument)
dtmAdded = DocumentTermMatrix(corpusAdded)
str(dtmAdded)
sparseAdded = removeSparseTerms(dtmAdded, 0.997)
wordsAdded = as.data.frame(as.matrix(sparseAdded))
colnames(wordsAdded) = make.names(colnames(wordsAdded))
colnames(wordsAdded) = paste("A", colnames(wordsAdded))
corpusRemoved = Corpus(VectorSource(wiki$Removed))
corpusRemoved = tm_map(corpusRemoved, removeWords, stopwords("english"))
corpusRemoved = tm_map(corpusRemoved, stemDocument)
dtmRemoved = DocumentTermMatrix(corpusRemoved)
sparseRemoved = removeSparseTerms(dtmRemoved, 0.997)
wordsRemoved = as.data.frame(as.matrix(sparseRemoved))
colnames(wordsRemoved) = make.names(colnames(wordsRemoved))
colnames(wordsRemoved) = paste("A", colnames(wordsRemoved))
wikiwords = cbind(wordsAdded,wordsRemoved)
wikiwords$Vandal = wiki$Vandal
library(caTools)
set.seed(123)
split = sample.split(wikiwords$Vandal, SplitRatio = 0.7)
traindata = subset(wikiwords, split == TRUE)
testdata = subset(wikiwords, split == FALSE)
table(testdata$Vandal)
library(rpart)
library(rpart.plot)
wikiCart = rpart(Vandal~., data = traindata, method = "class")
predictCart = predict(wikiCart, newdata = testdata, type = "class")
table(testdata$Vandal, predictCart)
prp(wikiCart)
wikiwords2 = wikiwords
wikiwords2$HTTP = ifelse(grepl("http", wiki$Added, fixed = TRUE),1,0)
table(wikiwords2$HTTP)
traindata2 = subset(wikiwords2, split == TRUE)
testdata2 = subset(wikiwords2, split == FALSE)
wikiCart2 = rpart(Vandal~. ,data = traindata2, method = "class")
predictCart2 = predict(wikiCart2, newdata = testdata2, type = "class")
table(testdata2$Vandal, predictCart2)
wikiwords2$numAdded = rowSums(as.matrix(dtmAdded))
wikiwords2$numRemoved = rowSums(as.matrix(dtmRemoved))
mean(wikiwords2$numAdded)
traindata3 = subset(wikiwords2, split == TRUE)
testdata3 = subset(wikiwords2, split == FALSE)
wikiCart3 = rpart(Vandal~. ,data = traindata3, method = "class")
predictCart3 = predict(wikiCart3, newdata = testdata3, type = "class")
table(testdata3$Vandal, predictCart3)
wikiwords3 = wikiwords2
wikiwords3$Minor = wiki$Minor
wikiwords3$Loggedin = wiki$Loggedin
traindata4 = subset(wikiwords3, split == TRUE)
testdata4 = subset(wikiwords3, split == FALSE)
wikiCart4 = rpart(Vandal~. , data = traindata4, method = "class")
predictCart4 = predict(wikiCart4, newdata = testdata4, type = "class")
table(testdata4$Vandal, predictCart4)
prp(wikiCart4)
library(randomForest)
wikiglm = glm(Vandal ~ . , data = traindata4, family = "binomial")
predictglm = predict(wikiglm, newdata = testdata4, type = "response")
table(testdata4$Vandal, predictglm>0.5)
wikiRF = randomForest(Vandal ~ ., data = traindata4)
predictRF = predict(wikiRF, newdata = testdata4)
